name: CI - Bookstore PHP 8 + MySQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.1", "8.2"]
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ${{ vars.DB_DATABASE || 'bookstore_ci' }}
        ports: ["3306:3306"]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo_mysql, mbstring, intl, curl
          coverage: none

      - name: Wait for MySQL
        run: |
          for i in `seq 1 30`; do
            mysqladmin ping -h 127.0.0.1 -uroot -proot && break
            sleep 2
          done

      - name: Create database & config
        run: |
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS ${{ vars.DB_DATABASE || 'bookstore_ci' }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
          mkdir -p config
          cat > config/database.php <<'PHP'
          <?php
          return [
              'DB_HOST' => '127.0.0.1',
              'DB_PORT' => '3306',
              'DB_NAME' => getenv('DB_DATABASE') ?: (getenv('GITHUB_VARIABLES_DB_DATABASE') ?: 'bookstore_ci'),
              'DB_USER' => getenv('DB_USERNAME') ?: 'root',
              'DB_PASS' => getenv('DB_PASSWORD') ?: 'root',
              'DB_CHARSET' => 'utf8mb4',
          ];
          PHP

      - name: PHP lint
        run: |
          find . -type f -name "*.php" -print0 | xargs -0 -n1 -P4 php -l

      - name: Run migrations
        run: php scripts/migrate.php up

      - name: Seed demo data
        run: php scripts/migrate.php seed

      - name: Smoke check - list tables
        run: |
          mysql -h 127.0.0.1 -uroot -proot -e "SHOW TABLES IN ${{ vars.DB_DATABASE || 'bookstore_ci' }};"

      # Add your test suite here (PHPUnit/Codeception) if present
